### ISSUE TITLE
[bug] No types included in version 2.0.0

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-react-editable-components#125]
**Describe the bug**
When using version 2.0.0, no type definitions are included in the package.
They were included in the previous version (1.1.10).

The `package.json` still specifies where the type information should be found, but no file exists at that path.

**Package version**
2.0.0

**To Reproduce**
Use version 2.0.0 in a typescript project and watch typescript lose it's mind.

**Expected behavior**
The types should be available.

**Additional context**

----

Tarball Contents for V1.1.10

> $ npm pack --dry-run  @adobe/aem-react-editable-components@1.1.10
> npm notice
> npm notice �  @adobe/aem-react-editable-components@1.1.10
> npm notice === Tarball Contents ===
> npm notice 5.0kB  CHANGELOG.md
> npm notice 11.3kB LICENSE
> npm notice 2.1kB  README.md
> npm notice 16.9kB dist/aem-react-editable-components.js
> npm notice 1.9kB  dist/ComponentMapping.d.ts
> npm notice 1.2kB  dist/ComponentMapping.d.ts.map
> npm notice 1.1kB  dist/components/allowedcomponents/AllowedComponentsContainer.d.ts
> npm notice 736B   dist/components/allowedcomponents/AllowedComponentsContainer.d.ts.map
> npm notice 601B   dist/components/allowedcomponents/AllowedComponentsPlaceholder.d.ts
> npm notice 491B   dist/components/allowedcomponents/AllowedComponentsPlaceholder.d.ts.map
> npm notice 690B   dist/components/allowedcomponents/AllowedComponentsPlaceholderList.d.ts
> npm notice 623B   dist/components/allowedcomponents/AllowedComponentsPlaceholderList.d.ts.map
> npm notice 2.4kB  dist/components/Container.d.ts
> npm notice 1.3kB  dist/components/Container.d.ts.map
> npm notice 590B   dist/components/ContainerPlaceholder.d.ts
> npm notice 457B   dist/components/ContainerPlaceholder.d.ts.map
> npm notice 4.2kB  dist/components/EditableComponent.d.ts
> npm notice 861B   dist/components/EditableComponent.d.ts.map
> npm notice 4.7kB  dist/components/ModelProvider.d.ts
> npm notice 979B   dist/components/ModelProvider.d.ts.map
> npm notice 990B   dist/components/Page.d.ts
> npm notice 831B   dist/components/Page.d.ts.map
> npm notice 1.0kB  dist/components/ResponsiveGrid.d.ts
> npm notice 774B   dist/components/ResponsiveGrid.d.ts.map
> npm notice 1.8kB  dist/Constants.d.ts
> npm notice 683B   dist/Constants.d.ts.map
> npm notice 247B   dist/EditorContext.d.ts
> npm notice 294B   dist/EditorContext.d.ts.map
> npm notice 464B   dist/types.d.ts
> npm notice 358B   dist/types.d.ts.map
> npm notice 1.1kB  dist/Utils.d.ts
> npm notice 458B   dist/Utils.d.ts.map
> npm notice 3.2kB  package.json
> npm notice === Tarball Details ===
> npm notice name:          @adobe/aem-react-editable-components
> npm notice version:       1.1.10
> npm notice filename:      @adobe/aem-react-editable-components-1.1.10.tgz
> npm notice package size:  19.7 kB
> npm notice unpacked size: 70.4 kB
> npm notice shasum:        fcdae680854fb6d29390b60acec7507f9215e88b
> npm notice integrity:     sha512-NelOm1tk5IG3T[...]TL+bTp3bYZXyw==
> npm notice total files:   33
> npm notice
> adobe-aem-react-editable-components-1.1.10.tgz

----

Tarball Contents for V2.0.0

> $ npm pack --dry-run  @adobe/aem-react-editable-components@2.0.0
> npm notice
> npm notice �  @adobe/aem-react-editable-components@2.0.0
> npm notice === Tarball Contents ===
> npm notice 11.3kB LICENSE
> npm notice 2.8kB  README.md
> npm notice 9.1kB  dist/aem-react-editable-components.js
> npm notice 2.7kB  dist/coverage/lcov-report/block-navigation.js
> npm notice 17.6kB dist/coverage/lcov-report/prettify.js
> npm notice 6.2kB  dist/coverage/lcov-report/sorter.js
> npm notice 3.7kB  package.json
> npm notice === Tarball Details ===
> npm notice name:          @adobe/aem-react-editable-components
> npm notice version:       2.0.0
> npm notice filename:      @adobe/aem-react-editable-components-2.0.0.tgz
> npm notice package size:  19.2 kB
> npm notice unpacked size: 53.4 kB
> npm notice shasum:        e222daa6f1bc3873c454ef9170003686f1d409db
> npm notice integrity:     sha512-tCRAJMhJe0p1A[...]UjCqj8Nj/Ap4A==
> npm notice total files:   7
> npm notice
> adobe-aem-react-editable-components-2.0.0.tgz

**Comment by iamdavidjackson** [comment]
This is an issue for my project as well.  Can please generate a package with type definitions?

**Comment by ky940819** [comment]
I think the issue probably originates here:
https://github.com/adobe/aem-react-editable-components/commit/302a43a51110b7baf8c8ebb52b88642fa1e28d8f#diff-83a02285ff0dfdfd9c08d3f4ba77f65074b72e4b8f378fbf919a5e8645e1edd4

The types are no longer being output into the `dist` folder, and are therefore not included in the package.
