### ISSUE TITLE
[Teaser] The image authored in the Teaser react core component is not rendered in the webpage

### ISSUE THREAD

**Issue by khn2475** [adobe/aem-react-editable-components#38]
**Describe the bug**
I configured an image in the teaser react core component but the image is not being rendered in the webpage. The teaser core component model is not returning the imagePath value and hence the teaser typescript code is failing the render the image.

**Package version**
AEM Cloud
Core Components version 2.11.1
JRE version Java(TM) SE Runtime Environment (build 11.0.6+8-LTS)

**To Reproduce**
1. Go to 'http://localhost:4502/editor.html/content/aem-react-core-spacomponents-example/library/teaser.html' 
2. Author the teaser example component
3. Drop the asset from DAM
4. Image is not displayed in the webpage

**Expected behavior**
When the image is authored in teaser component, it has to be displayed in the webpage.

**Screenshots**
![Screenshot (140)](https://user-images.githubusercontent.com/73276680/97171258-24dd4d80-17b3-11eb-9ff5-1a8d9f69bb92.png)
![Screenshot (136)](https://user-images.githubusercontent.com/73276680/97171269-2b6bc500-17b3-11eb-8be4-7836d4655860.png)

**Comment by pfauchere** [comment]
This seems to be an issue with the Sling Model of the Teaser Core Component. Please open an issue in [0]

[0] https://github.com/adobe/aem-core-wcm-components
