### ISSUE TITLE
MapperFunction Typescript return type inconsistency

### ISSUE THREAD

**Issue by seanblonien** [adobe/aem-react-editable-components#47]
**Describe the bug**
MapperFunction Typescript return type inconsistency

**Package version**
1.1.2

**To Reproduce**
N/A

**Expected behavior**
The documentation says MapTo's MappFunction returns a component, and yet the return type is `void`

**Screenshots**
MapperFunction return type of void
https://github.com/adobe/aem-react-editable-components/blob/d7d176e48a79aad303bfe94a420e8444c6bead1c/src/ComponentMapping.tsx#L90

Documentation clearly using the return value as non-void
![image](https://user-images.githubusercontent.com/33133478/103926752-35bd1000-50ce-11eb-8e59-6356925e4d56.png)

**Additional context**
N/A

**Comment by niekraaijmakers** [comment]
You are right, seems it does return the 'decorated' component. Seems we should change that type to something like
`type MapperFunction<P extends MappedComponentProperties> = (component: ComponentType<P>, editConfig?: EditConfig<P>) => ComponentType<P>;`

**Comment by pfauchere** [comment]
Internally tracked by CQ-4316490
