### ISSUE TITLE
Query/Feature Request - remove/hide Drag Components button with config

### ISSUE THREAD

**Issue by TobyGWilliams** [adobe/aem-react-editable-components#58]
Hello, 

I am working with the SPA for my component, the component uses the Responsive Grid to wrap two child components.

e.g. 
Responsive Grid ->
 - Sub Component 1
 - Sub Component 2

However, in this application, we will always have only two components but the spa adds the 'drag components' button, which takes up space and looks out of place.

Is there a way to tell the spa to not add the 'drag components' for the responsive grid?

Alternatively is there any configuration in AEM that might achieve the same effect?

**Comment by pfauchere** [comment]
Hi, @TobyGWilliams

> Is there a way to tell the spa to not add the 'drag components' for the responsive grid?

Do you then need the responsive grid at all? Instead, you may want to extend the Container class and get rid of the notion of ContainerPlaceholder. Backend side, you can decide to keep the current container model or optimize the payload by exposing a simpler Sling Model.

> Alternatively is there any configuration in AEM that might achieve the same effect?

Not OOTB

[0] https://github.com/adobe/aem-react-editable-components/blob/master/src/components/Container.tsx
[1] https://github.com/adobe/aem-react-editable-components/blob/master/src/components/Container.tsx#L148

**Comment by TobyGWilliams** [comment]
Thank you for your help, this prodded me to realise that I need to modify our extension of the responsive grid component for this case. In the end it was pretty simple, check for scenario and then omit placeholder.

Thank you for your help.
