### ISSUE TITLE
Responsive Grid column classes for device breakpoints overridden by component Style System feature

### ISSUE THREAD

**Issue by schoudry** [adobe/aem-react-editable-components#78]
**Describe the bug**
Component style system feature was added with PR https://github.com/adobe/aem-react-editable-components/pull/69/files
It overrides the grid classes for various responsive breakpoints

**Package version**
&gt;= 1.1.7

**To Reproduce**
1. Create a template with Desktop and other breakpoints (eg. Tablet, Mobile....)
2. Add any sample component on a page created using template in step 1
3. Configure the component on various breakpoints eg. Tablet
4. In View source you can see the breakpoint styles missing...

**Expected behavior**
Styles from "component style system" and "grid style system" should be combined

**Screenshots**
![image](https://user-images.githubusercontent.com/6585493/131560169-0d5c36fd-b09f-46b1-a59c-693cea92c6a3.png)

**Additional context**

**Comment by friendlymahi** [comment]
@schoudry - Now that the issue is fixed, can we close this issue? Thanks !

@niekraaijmakers

**Comment by schoudry** [comment]
hey @friendlymahi i'll close it this week (after some internal validation by customer QA)

**Comment by schoudry** [comment]
fixed now
